### ISSUE TITLE
open Refworks in a new window

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#113]
Exporting to Refworks did not open in a new tab so it replaced the catalogue interface and I had to back arrow too many times to get back to it.  Can it be set to open in a new browser tab or window?

From beta-test feedback

**Comment by redlibrarian** [comment]
Hm. I can't immediately figure this one out. Still working on it.

**Comment by redlibrarian** [comment]
So, the Refworks (and Endnote) functionality is provided by the blacklight-marc gem, in the app/views/bookmarks/_refworks.html.erb file. Ordinarily, we would just copy this file into our repo and add target => "_blank" to the refworks link, but this isn't working. I don't know if it's because of the way Rails engines handle gems or something else; in any event *that gem* is the only place refworksLink (the HTML id) is referenced. I don't know why this isn't working...

**Comment by redlibrarian** [comment]
None of this is working as expected, and I think it's because there are too many gems/rails engines in the mix. @nnunn If you can do this with JS, that would be great.

**Comment by nnunn** [comment]
This is working in test. Will close once it's in production.

**Comment by seanluyk** [comment]
In production. Closing
