### ISSUE TITLE
RIS format for citation 

### ISSUE THREAD

**Issue by kzarft** [ualbertalib/NEOSDiscovery#121]
Feedback from Director's meeting. Could RIS format be an option for citation?

**Comment by redlibrarian** [comment]
@kzarft I've added a library to enable RIS file downloads. The actual field mapping may need some tweaking, so I'll have you (and others) take a look when it's in production.

**Comment by redlibrarian** [comment]
@kzarft "Download in RIS format" is now an option in the left hand column of tools. Can you test it and let me know if the field mapping is working OK?

**Comment by redlibrarian** [comment]
For discussion on Friday

**Comment by kzarft** [comment]
@redlibrarian I did some brief testing the of the RIS format.  It is coming through with a GEN (Generic) reference type in the first tag which will load into Zotero but doesn't load into our APA Style Central product.  If I edit the reference type to be BOOK, then it does load into APA Style Central.  I can have our Instruction librarian who is an expert in APA take a look at the tags and field mapping next week when she is back from vacation, if that would help?

**Comment by redlibrarian** [comment]
Thanks @kzarft that would be helpful. I know where to update the fields, so I can make those changes once she's had a look.

**Comment by redlibrarian** [comment]
For future reference, the RIS mappings are specified here: https://github.com/ualbertalib/NEOSDiscovery/blob/master/app/models/solr_document.rb#L38

If we don't hear about new mappings by the time I go on leave @nnunn or @seanluyk can update this file and cut a new release.

**Comment by kzarft** [comment]
@redlibrarian from you RIS mappings link, it looks like it should be choosing BOOK or JOUR as the Reference type, if that is the format in the record, but that doesn't seem to be working.  Everything that I have downloaded in RIS format so far has been given the reference type of GEN (generic) even though I have selected a number of books and a journal.

The Primary Author (which I think is being called in the **:AU => 'author_display',** line doesn't seem to be working either.  I only see the additional authors in the file.

The title is missing the subtitle. 
ET Edition is not working either.

Our instruction librarian took a look and thinks that if it is possible we should also include the reference types of EBOOK, RPRT, and VIDEO.

She recommended the following tags in addition to the ones already in your mapping:
CY Place Published (required)
ED Editor
JO Journal/Periodical Name
UR URL (for ebooks)
VL Volume number 
VO Published Standard Number

She also recommended the tags DO (DOI), EP (End Page), SP (Start Page) and IS (Issue Number) if we have any articles in the catalogue.  I don't believe we do, but Tech Services may know.

Let me know if you need examples for any of these!

**Comment by redlibrarian** [comment]
A couple of things I've gathered from our cataloguing;
- There is no "E-book" format: an electronic book has a format of "book" and happens to be online.
- Editors don't seem to be identified in our MARC records separately, at least not in Blacklight - they are just Additional Authors. I assume they have specified roles in RDA, but until we upgrade to using RDA mappings in Blacklight, we don't have access to them. 
- We don't seem to have a "Report" format.
- We don't have a separate field for Journal/Periodical name - it's in "title_display", same as monographs.
- We pull the 856 fields in in real time instead of indexing them, so the URL isn't available to RIS. 

I think I'm just going to have to get it going as best I can, and it will have to be revisited later (perhaps when we're able to take advantage of RDA fields).
