### ISSUE TITLE
[NEOS Discovery] SMS not working

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#132]
Emailing records work fine, but SMS fails with no error. In development, I can see see the outgoing SMS email message, and since both services work via email, I'm not sure why one would fail and one succeed. I'm going to have our sysadmin look into this.

**Comment by redlibrarian** [comment]
Just checked the latest release... still not working.

**Comment by redlibrarian** [comment]
OK. I managed to test this on my workstation, and it's working fine. The problem must be on the server end.

**Comment by redlibrarian** [comment]
I just tested the UAL Discovery and SMS isn't working there either (it was working ever since we launched). I think there may have a been a network change that has broken this functionality.

**Comment by nmacgreg** [comment]
Reference: https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=46355#219994

We implemented the Prod server, haxby, in a non-routable address space, partly so that the IDS/IPS in Ray's firewall would be activated after stripping the SSL at the HAproxy servers.  While the OS is able to send email via on-campus routing (IST), it seems the application is routing SMTP *directly* to the Internet, which isn't possible from the non-routable address.

Can you modify the application to send mail to the MTA on localhost, and let it handle routing?

**Comment by nnunn** [comment]
During my research into the customization of UAL Blacklight and NEOS Blacklight, I came across a difference between the two systems. UAL Blacklight had a model called record_mailer.rb and NEOS does not. It appears that this model is part of the process of sending email and sms messages -- could this be why we are having these issues?

**Comment by pgwillia** [comment]
I think these values missing from `config/environments/production.rb` might also related to this issue
```
config.action_mailer.delivery_method = :sendmail
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = true
config.action_mailer.default_options = {from: 'no-reply@ualberta.ca'}
```

**Comment by pgwillia** [comment]
Replying to https://github.com/ualbertalib/NEOSDiscovery/issues/132#issuecomment-428981799
As long as `I18n.t('blacklight.email.text.default_title')` and `I18n.t('blacklight.email.text.subject')` have been set, there don't think there needs to be a copy of the RecordMailer model. There is some customization there though.

**Comment by pgwillia** [comment]
```
Sent mail to tricia.jenkins@ualberta.ca (15.7ms)
Date: Thu, 11 Oct 2018 15:50:55 -0600
From: no-reply@ualberta.ca
To: tricia.jenkins@ualberta.ca
Message-ID: <5bbfc5bfe329d_4fd52afe0d521fa8325be@DIG002TJ1.mail>
Subject: Item Record: ["Parenting"]
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Title: Parenting
Author: Dugger, Jim
Format: Book
Language: English
URL: http://localhost:3000/catalog/2533825
Message: Message: Test default email this
```
vs
```
Sent mail to tricia.jenkins@ualberta.ca (12.6ms)
Date: Thu, 11 Oct 2018 15:50:04 -0600
From: no-reply@ualberta.ca
To: tricia.jenkins@ualberta.ca
Message-ID: <5bbfc58c8cc49_4f1f2af190d03fac1764f@DIG002TJ1.mail>
Subject: From University of Alberta Libraries: Parenting
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

From University of Alberta Libraries.

Here is the item you emailed from the University of Alberta Libraries website.

  Title: Parenting
Author: Dugger, Jim
Format: Book
Language: English
URL: http://localhost:3000/catalog/2533825


  Message: Message: Test UAL discovery email this
```

**Comment by seanluyk** [comment]
Confirmed that text messages are not being sent - accessing from off campus

**Comment by pgwillia** [comment]
Need to speak with UNIX team about options for configuration. (Is there better config for Discovery as well?) What mail server(s) are available?

Avalon might be a source of information.  The batch ingest sends emails.

**Comment by nmacgreg** [comment]
I've left multiple updates @ https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=46355;ArticleID=234650
In short, 
* I found the postfix MTA was unconfigured in both Test & Prod.  
* I fixed that in the playbook, played it against both Test & Prod, and confirmed that the problem was resolved (I can send mail "anywhere" from the commandline)
* I found "Email me this item" __crashing__ in Test, traced it to forgetting to set the "from:" address, in config/environments/test.rb (please update)
* In both Test & Prod, I can use "Email me this item" to a ualberta.ca address, successfully, but email to external addresses fail.  And, /var/log/maillog reveals that the Rails app isn't using the local Postfix MTA.

I strongly recommend rewriting/configuring whatever component sends mail, to send mail through the local MTA.

**Comment by seanluyk** [comment]
Weird, I just tested sending an item to my personal Gmail address and over SMS and both worked instantly

**Comment by Andeebee** [comment]
Yes - confirmed! Text me this item just worked for me.

**Comment by nmacgreg** [comment]
Oops, Prod had queued all the emails/SMS that weren't delivered, and it just finished delivering the entire backlog!
