### ISSUE TITLE
[NEOS Blacklight]　Mix up between AHS closed libraries and Northern Lakes libraries - Result list displaying AHS, under Copies Owned By

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#152]
We are seeing incorrect information being displayed in the results list under copies owned. This is displaying old AHS libraries (e.g. Cross Cancer, Women's Health) in place of the correct holding library at Northern Lakes (e.g. Grouard, Slave Lake). When you go into the record, the holding table displays the correct Northern Lakes information.

Not happening in old iLink.

Example record: 7532885

**Comment by seanluyk** [comment]
@Andeebee thanks for reporting. Here is the record from UAL Discovery, which makes me think we fixed this issue here but not for NEOS: https://library.ualberta.ca/catalog/7532885

@weiweishi @pgwillia could this small fixed be added to our current sprint?

**Comment by weiweishi** [comment]
@seanluyk Do you mind throwing the URL to the record in NEOS blacklight - sorry for my negligence. but  I actually don't know which URL it is hosted...

**Comment by seanluyk** [comment]
@weiweishi here it is: https://catalogue.neoslibraries.ca/catalog/7532885

To clarify the issue, the locations are wrong in the **results view** under copies owned by field, not in the record view: https://catalogue.neoslibraries.ca/?utf8=%E2%9C%93&lib=abhealth&search_field=all_fields&q=7532885

In both NEOS and UAL BL, different files are used to specify locations, which creates lots of issues IMO. We've had these out of sync here quite a bit too. Time for that database!

**Comment by pgwillia** [comment]
It doesn't look to me like this was fixed in UAL BL.
![screenshot from 2018-09-28 15-00-08](https://user-images.githubusercontent.com/1220762/46233271-37180380-c32f-11e8-8c9d-a19fb95b7283.png)

The locations in the "Held by" section comes from 596a and appear to be integers which we then map to values found [here](https://github.com/ualbertalib/discovery/blob/master/config/library_codes.yml). I'm not even sure how to start to verify the correctness of this file.

The locations in the "Library" facet come from 926m and appear to be alpha-numeric codes which we normalize and then map to values found [here](https://github.com/ualbertalib/discovery/blob/master/config/locations.yml). These values appear to be correct!

**Comment by pgwillia** [comment]
In this case the 'locations' happen to be the same as what is intended by 'held_by'.  Is this the case more generally?

**Comment by seanluyk** [comment]
@pgwillia oy, what a mess! Locations and held by are the exact same thing, so I'm not sure why we get that information from multiple places. Thought this was finally fixed for UAL but I must have been mistaken
