### ISSUE TITLE
sort by year working?

### ISSUE THREAD

**Issue by kzarft** [ualbertalib/NEOSDiscovery#86]
If you do a search for "invitation to health" and then try sorting by year, it doesn't seem to be bringing the  Fifth Canadian Edition (2018) or the Fourth Canadian Edition (2015) to the top of the list.  Is this because it is sorting the 260 field first and then the 264 fields?

Example search: https://barking.library.ualberta.ca/?q=%22invitation+to+health%22&search_field=all_fields&sort=pub_date_sort+desc%2C+title_sort+asc

**Comment by redlibrarian** [comment]
We're currently relying on our existing Blacklight index, which uses the indexing rules from the UAL Blacklight (which use the AACR2 mandated fields like 260 instead of the RDA fields like 264). This will be fixed when we upgrade UAL Blacklight and start using traject for marc mapping. Until then, we can't fix this in NEOS Blacklight.
